# Generated by Django 5.2.4 on 2025-08-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_my_borrows"),
    ]

    operations = [
        migrations.DeleteModel(
            name="my_borrows",
        ),
    ]
